language: generic

services:
  - docker

script:
  - export DOCKER_BUILDKIT=1 && docker-compose build

deploy:
  - provider: script
    script: bash ci/deploy.sh
    on:
      branch: main

  - provider: script
    skip_cleanup: true
    script: bash ci/deploy.sh
    on:
      tags: true
