language: generic

services:
  - docker

script:
  - DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build

deploy:
  - provider: script
    script: bash ci/deploy.sh
    on:
      branch: main

  - provider: script
    skip_cleanup: true
    script: bash ci/deploy.sh
    on:
      tags: true
